# Generated by Django 3.0.6 on 2020-05-26 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweet_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
