# Generated by Django 3.0.6 on 2020-05-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitteruser',
            old_name='dependencies',
            new_name='following',
        ),
    ]
